version: '3.1'

volumes:
  ldap_data_test:
  ldap_config_test:

services:
  ldap:
    image: georchestra/ldap:latest
    build: ./
    secrets:
      - slapd_password
      - georchestra_privileged_user_passwd
    environment:
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_ORGANIZATION=georchestra
      - SLAPD_ADDITIONAL_MODULES=groupofmembers,openssh
      - SLAPD_PASSWORD_FILE=/run/secrets/slapd_password
      - SLAPD_PASSWORD=
      - GEORCHESTRA_PRIVILEGED_USER_PASSWORD_FILE=/run/secrets/georchestra_privileged_user_passwd
      - SLAPD_LOG_LEVEL=32768
    volumes:
      - ldap_data_test:/var/lib/ldap
      - ldap_config_test:/etc/ldap
    ports:
      - '10389:389'

secrets:
  slapd_password:
    file: ./secrets/slapd_password.txt
  georchestra_privileged_user_passwd:
    file: ./secrets/georchestra_privileged_user_passwd.txt
